name: Feature Request / Suggestion
description: Suggest an idea for this project / Suggérer une idée pour ce projet
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? / Est-ce lié à un problème ?
      description: A clear and concise description of what the problem is.
      placeholder: Ex: I'm always frustrated when... / Ex: Je suis frustré quand...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like / La solution que vous aimeriez
      placeholder: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Additional context / Contexte additionnel
      placeholder: Add any other context or screenshots about the feature request here.
